ard:
  fqbn: "--fqbn=arduino:avr:uno --fqbn=Infineon:xmc:XMC1100_XMC2GO --fqbn=Infineon:xmc:XMC1100_Boot_Kit --fqbn=Infineon:xmc:XMC1300_Boot_Kit --fqbn=Infineon:xmc:XMC1400_XMC2GO --fqbn=Infineon:xmc:XMC1400_Arduino_Kit --fqbn=Infineon:xmc:XMC4200_Platform2GO --fqbn=Infineon:xmc:XMC4400_Platform2GO --fqbn=Infineon:xmc:XMC4700_Relax_Kit"

pio:
  boards: "--board=uno --board=xmc1100_xmc2go --board=xmc1100_boot_kit --board=xmc4700_relax_kit"
  options: "--project-option=\"lib_deps=Wire\""

hil:
  fqbn:         Infineon:xmc:XMC1100_XMC2GO
  example:      "examples/readAngleTest"
  baud:         9600